# testarg_a
# testarg_b
# testarg_c
# testarg_d
# testarg_e
run: compile

	# a.
	#./testarg_a 6 toto salut2016 ?!:;

	# b.

	# c.
	#./testarg_c 6.2 -8 2.0

	# d.

	# e.
	./testarg 6a84 blbllcc 0.34.2
	./testarg 0.345 234
	./testarg 023. 345
	./testarg -0.32 234
	./testarg -0.32.34 234
	

compile: testarg.c	
	gcc -Wall -g -o testarg_a testarg_a.c

clean: 
	rm testarg_a
	ls -l